name: Terraform
on: master

jobs:
  on-pull-request:
    name: on-pull-request
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
      uses: actions/checkout@v1
      
    - name: Filter to PR Opened
      uses: actions/bin/filter@master
      with:
        args: "action 'opened|synchronize'"
    
    - name: Terraform - Format
      uses: hashicorp/terraform-github-actions/fmt@v0.3.5
      env:
        TF_ACTION_WORKING_DIR: "."

    - name: Terraform - Init
      uses: hashicorp/terraform-github-actions/init@v0.3.5
      env:
        TF_ACTION_WORKING_DIR: "."

    - name: Terraform - Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.5
      env:
        TF_ACTION_WORKING_DIR: "."

    - name: Terraform - Plan
      uses: hashicorp/terraform-github-actions/plan@v0.3.5
      env:
        TF_ACTION_WORKING_DIR: "."
